trigger:
  - master
  - develop

jobs:
  - job: "Windows"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - bash: |
          set -e
          curl -sLo LockedList.zip https://nsis.sourceforge.io/mediawiki/images/d/d3/LockedList.zip
          unzip LockedList.zip "Plugins/*" -d "C:\Program Files (x86)\NSIS" -q
          unzip LockedList.zip "Plugins/x86-ansi/*" -d "C:\Program Files (x86)\NSIS" -q
          unzip LockedList.zip "Plugins/x86-unicode/*" -d "C:\Program Files (x86)\NSIS" -q
          curl -sLo pahkat.exe https://github.com/divvun/pahkat/releases/download/0.6.0/pahkat.exe
          curl -sLo divvun-bundler.exe https://github.com/divvun/divvun-bundler/releases/download/0.1.0/divvun-bundler.exe
          curl -sLo rustup-init.exe https://win.rustup.rs/
          ./rustup-init.exe -y --default-host=i686-pc-windows-msvc --default-toolchain=stable-i686-pc-windows-msvc
          git clone https://github.com/divvun/divvun-ci-config.git
          openssl aes-256-cbc -d -in ./divvun-ci-config/config.txz.enc -pass pass:$DIVVUN_KEY -out config.txz -md md5
          7z e config.txz
          tar xf config.tar
        displayName: "Install prerequisites"
        env:
          DIVVUN_KEY: $(divvunKey)
      - script: |
          PATH=%PATH%;%USERPROFILE%\.cargo\bin
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
          rustup default nightly-i686-pc-windows-msvc
          cargo build --target=i686-pc-windows-msvc --release
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          rustup default nightly-x86_64-pc-windows-msvc
          cargo build --target=x86_64-pc-windows-msvc --release
        displayName: "Build"
      - powershell: |
          $Env:PATH += ";C:\Program Files (x86)\Microsoft SDKs\ClickOnce\SignTool"
          $Env:PATH += ";$(System.DefaultWorkingDirectory)"
          $version = Select-String -Path .\Cargo.toml -Pattern "^version.*=.*$"
          $version = $version.Matches[0].Value.Replace('"', '').Replace(' ','').Replace('version=','')
          divvun-bundler -t win -H "WinDivvun Speller Engine" -V $version --uuid "{FB90E8B8-EBE5-51BC-9BDE-28535417088D}" -R -c .\enc\creds\windows\divvun.pfx checker --a32 .\target\i686-pc-windows-msvc\release\windivvun.dll --a64 .\target\x86_64-pc-windows-msvc\release\windivvun.dll
          Rename-Item windivvun-$version.exe windivvun.exe
        displayName: "Bundle"
        env:
          SIGN_PFX_PASSWORD: $(pfxPassword)
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: "$(System.DefaultWorkingDirectory)/windivvun.exe"
          artifactName: windows
      - powershell: |
          . .\divvun-ci-config\repo\scripts\PahkatDeploySvn.ps1
          $Env:PATH += ";$(System.DefaultWorkingDirectory)"
          $version = Select-String -Path .\Cargo.toml -Pattern "^version.*=.*$"
          $version = $version.Matches[0].Value.Replace('"', '').Replace(' ','').Replace('version=','')
          PahkatDeploySvn -SvnUrl https://pahkat.uit.no/repo/windows -Artifact "$(System.DefaultWorkingDirectory)\windivvun.exe" -Package windivvun -Version $version
          PahkatDeploySvn -SvnUrl https://pahkat.uit.no/repo/canada-win -Artifact "$(System.DefaultWorkingDirectory)\windivvun.exe" -Package windivvun -Version $version
        displayName: "Deploy to nightly channel"
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          DEPLOY_SVN_USER: $(svnUser)
          DEPLOY_SVN_PASSWORD: $(svnPassword)
          DEPLOY_SVN_COMMIT: $(svnCommit)
