[package]
name = "win-spellcheck"
version = "0.1.0"
authors = ["Eike Siewertsen <eike@technocreatives.com>"]
edition = "2018"

[dependencies]
log = "0.4"
dirs = "1.0.4"

[dependencies.log4rs]
version = "0.8.1"

[dependencies.com-impl]
git = "https://github.com/bbqsrc/com-impl-rs"

[dependencies.winapi]
version = "0.3.6"
features = ["winerror", "unknwnbase", "objbase", "oleauto", "winerror", "shlobj", "shtypes", "combaseapi", "knownfolders"]

[dependencies.hfst-ospell-rs]
git = "https://github.com/bbqsrc/hfst-ospell-rs"

[build-dependencies.winapi-tlb-bindgen]
git = "https://github.com/Arnavion/winapi-tlb-bindgen"