[package]
name = "windivvun"
version = "0.2.1"
authors = ["Eike Siewertsen <eike@technocreatives.com>"]
edition = "2018"

[lib]
name = "windivvun"
crate-type = ["dylib"]

[dependencies]
log = "0.4.8"
directories = "2.0.2"
lazy_static = "1.4.0"
parking_lot = "0.9.0"
log4rs = "0.8.3"
backtrace = "0.3.40"

[dependencies.com-impl]
git = "https://github.com/bbqsrc/com-impl-rs"

[dependencies.winapi]
version = "0.3.8"
features = ["winerror", "unknwnbase", "objbase", "oleauto", "winerror", "shlobj", "shtypes", "combaseapi", "knownfolders", "winuser", "winnls"]

[dependencies.divvunspell]
git = "https://github.com/divvun/divvunspell"
branch = "develop"
features = ["compression"]

[build-dependencies.winapi-tlb-bindgen]
git = "https://github.com/Arnavion/winapi-tlb-bindgen"
